{% set name = "portpicker" %}
{% set version = "1.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/portpicker-{{ version }}.tar.gz
  sha256: bd507fd6f96f65ee02781f2e674e9dc6c99bbfa6e3c39992e3916204c9d431fa

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - psutil

test:
  imports:
    - portpicker
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/google/python_portpicker
  summary: A library to choose unique available network ports.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jamesmyatt
